views:
  v1/pods:
    sortColumn: NAME:asc
    columns:
      - NAME
      - AGE
      - READY
      - STATUS
      - RESTARTS
      - CPU
      - MEM
      - "%CPU/R"
      - "%MEM/R"
      - "%CPU/L"
      - "%MEM/L"
      - NODE

